<?xml version="1.0" encoding="UTF-8"?>

<project name="xmvn-tools" default="package" basedir=".">

  <!-- ====================================================================== -->
  <!-- Cleaning up target                                                     -->
  <!-- ====================================================================== -->

  <target name="clean" description="Clean the output directory">
    <ant antfile="build.xml" dir="xmvn-resolve" target="clean"/>
    <ant antfile="build.xml" dir="xmvn-subst" target="clean"/>
    <ant antfile="build.xml" dir="xmvn-install" target="clean"/>
  </target>

  <!-- ====================================================================== -->
  <!-- Compilation target                                                     -->
  <!-- ====================================================================== -->

  <target name="compile" description="Compile the code">
    <ant antfile="build.xml" dir="xmvn-resolve" target="compile"/>
    <ant antfile="build.xml" dir="xmvn-subst" target="compile"/>
    <ant antfile="build.xml" dir="xmvn-install" target="compile"/>
  </target>

  <!-- ====================================================================== -->
  <!-- Javadoc target                                                         -->
  <!-- ====================================================================== -->

  <target name="javadoc" description="Generates the Javadoc of the application">
    <ant antfile="build.xml" dir="xmvn-resolve" target="javadoc"/>
    <ant antfile="build.xml" dir="xmvn-subst" target="javadoc"/>
    <ant antfile="build.xml" dir="xmvn-install" target="javadoc"/>
  </target>

  <!-- ====================================================================== -->
  <!-- Package target                                                         -->
  <!-- ====================================================================== -->

  <target name="package" description="Package the application">
    <ant antfile="build.xml" dir="xmvn-resolve" target="package"/>
    <ant antfile="build.xml" dir="xmvn-subst" target="package"/>
    <ant antfile="build.xml" dir="xmvn-install" target="package"/>
  </target>

</project>
